### ISSUE TITLE
Timer example is incorrect

### ISSUE THREAD

**Issue by systec-ms** [stm32-rs/stm32f7xx-hal#163]
If the interrupt is not cleared, it will immediately retriggered after the ISR has finished.
``` rust
    timer.clear_interrupt(Event::TimeOut);
```

**Comment by hannobraun** [comment]
Good catch, thank you!

**Comment by systec-ms** [comment]
@hannobraun could you add `good first issue` as a label, I can't. Thanks.

**Comment by hannobraun** [comment]
Good call!

**Comment by darryln** [comment]
@systec-ms  is there a repro case, or was this found by inspection?

**Comment by systec-ms** [comment]
> @systec-ms is there a repro case, or was this found by inspection?

Inspection.

**Comment by eldruin** [comment]
Fixed in #169. Closing.
