### ISSUE TITLE
Timer Makes Incorrect assumption about Clock Speed

### ISSUE THREAD

**Issue by dtjones190** [stm32-rs/stm32f7xx-hal#34]
The Timer assumes that the clock speed is equal to the peripheral clock, but that is only true in certain circumstances.
See Page 154 https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/96/8b/0d/ec/16/22/43/71/DM00224583/files/DM00224583.pdf/jcr:content/translations/en.DM00224583.pdf

![image](https://user-images.githubusercontent.com/37219309/75901773-0635db00-5e0d-11ea-92ff-2c4e0b78b61a.png)

**Comment by rfuest** [comment]
The issue has already been fixed in #36. I've just tested this again after the changes made in #50 and it seems to work as expected, so I think that this issue can be closed now.

**Comment by hannobraun** [comment]
Thanks for confirming this, @rfuest!
