### ISSUE TITLE
Modules are unavailable unless crate is imported with stm32f746

### ISSUE THREAD

**Issue by samuelburnham** [stm32-rs/stm32f7xx-hal#35]
Hi, Rust beginner here. I'm trying to use this excellent crate to blink an LED on an stm32f769; however, I get a "could not find `prelude` in `stm32f7xx_hal`" error when I import with the stm32f769 feature enabled. If I use the stm32f746 feature everything works perfectly, but wouldn't there be potential hardware issues from using code intended for another device?

**Comment by dtjones190** [comment]
Try my fork: 
https://github.com/dtjones190/stm32f7xx-hal
I am submitting a pull request now.

**Comment by eldruin** [comment]
I assume this was fixed in #36. Feel free to reopen otherwise.
