### ISSUE TITLE
STM32F7x0 support

### ISSUE THREAD

**Issue by SL-RU** [stm32-rs/stm32f7xx-hal#39]
Hello! Can you add STM32F730 support?

**Comment by hannobraun** [comment]
This is an open source project, so everyone who's interested (you, for example :slightly_smiling_face:) can add support for new hardware here.

**Comment by no111u3** [comment]
I found that we already support STM32F730 in our hal. This issue might be closing now.

**Comment by hannobraun** [comment]
Yes, added in #45. Thanks, @no111u3.
