### ISSUE TITLE
Release new versions

### ISSUE THREAD

**Issue by no111u3** [stm32-rs/stm32f7xx-hal#53]
Would you have plans to release new version of crate?

**Comment by mvertescher** [comment]
Yes, it's been a while since 0.1.0 and now seems like a good time to release a new version with all the PRs that have been merged.

**Comment by mvertescher** [comment]
Created #55 to track this. I should be able to get around to this in the next day or so.

**Comment by mvertescher** [comment]
v0.2.0 is now released. Feel free to open another issue in the future if you're looking for a new release!
