### ISSUE TITLE
Spi::enable takes Rcc as a parameter making it impossible to enable SPI after the clocks were frozen.

### ISSUE THREAD

**Issue by pftbest** [stm32-rs/stm32f7xx-hal#65]
I think there are 2 ways to solve this
1. Remove the Rcc argument and access the register internally using unsafe. `Serial::new` does this.
2. Split the Rcc struct, one part which configures the clock and another part which can turn on/off the peripherals.

**Comment by hardfau18** [comment]
this one is resolved i guess, may be its ok to close
